services:
  boilerplate-server:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    env_file:
      - ./.env
    depends_on:
      - boilerplate-db
    ports:
      - "5050:5050"
    networks:
      - boilerplate-net

  boilerplate-db:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: boilerplate_db
    volumes:
      - db-data:/data/db
    networks:
      - boilerplate-net

volumes:
  db-data:
    driver: local

networks:
  boilerplate-net:
    driver: bridge