CODE_SUCCESS_ADD_TEMPLATE = "SUCCESS_ADD_TEMPLATE"

CODE_ERROR_API = "ERROR_INTERNAL_SERVER"
CODE_ERROR_PYDANTIC = "ERROR_PYDANTIC"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"
CODE_ERROR_VALUE_IS_NOT_INTEGER = "ERROR_VALUE_IS_NOT_INTEGER"
CODE_ERROR_TEMPLATE_ALREADY_EXISTS = "ERROR_TEMPLATE_ALREADY_EXISTS"

CODE_NOT_FOUND_TEMPLATE = "NOT_FOUND_TEMPLATE"
